spring.application.name=fk-booster-example-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/fk_booster_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

grpc.server.port=9090
grpc.server.in-process-name=test
grpc.server.grpc-web.enabled=true
grpc.server.allow-any-origin=true
